sudo: required
dist: trusty

language: node_js
node_js:
  - '0.12'

before_install:
  # Codacy coverage
  - curl -sL https://github.com/jpm4j/jpm4j.installers/raw/master/dist/biz.aQute.jpm.run.jar >jpm4j.jar
  - java -jar jpm4j.jar -u init
  - ~/jpm/bin/jpm install com.codacy:codacy-coverage-reporter:assembly
  # / Codacy coverage

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd swagger-ui/
  - npm i -g jshint
  - npm install
  - cd ../storage
  - ./gradlew build --info
  - cd ../crawler
  - ./gradlew build --info

after_success:
  - ~/jpm/bin/codacy-coverage-reporter --language Java --coverageReport crawler/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
  - ~/jpm/bin/codacy-coverage-reporter --language Java --coverageReport storage/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
