sudo: required
dist: trusty

language: node_js
node_js:
  - '0.12'

before_install:
  # Codacy coverage
  - curl -sL http://repo1.maven.org/maven2/com/codacy/codacy-coverage-reporter/1.0.13/codacy-coverage-reporter-1.0.13-assembly.jar > ~/codacy-coverage-reporter.jar
  # / Codacy coverage

addons:
  apt:
    packages:
      - oracle-java8-installer

script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cd swagger-ui/
  - npm i -g jshint
  - npm install
  - cd ../storage
  - ./gradlew build --info
  - cd ../crawler
  - ./gradlew build --info
  - cd ../

after_success:
  - java -cp ~/codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter --language Java --coverageReport cli/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
  - java -cp ~/codacy-coverage-reporter.jar com.codacy.CodacyCoverageReporter --language Java --coverageReport server/build/reports/jacoco/test/jacocoTestReport.xml -t $CODACY_PROJECT_TOKEN
