twintip:
  mapping: /api
  yaml: "classpath:/api/storage-api.yaml"

spring:
  datasource:
    url: jdbc:hsqldb:mem:storage;sql.syntax_pgs=true
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate

endpoints:
  enabled: false
  health:
    enabled: true
  metrics:
    enabled: true
    sensitive: false

security:
  basic:
    enabled: false

lifecycle-check.delay: 300000

inactive.time: 86400
decommissioned.time: 172800
